title: Blog do Jonatan Machado
description: > # this means to ignore newlines until "baseurl:"
  Developer Full Stack / DevOps Student.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jonatanmachado.tk" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jonatan Machado # add your name
author-img: avatar.jpg # add your photo
about-author: Develop Frontend end Backend new project, kill bugs, implement new concepts and technologies to improve code quality, good development practices in Magento 2 end Magento Cloud.

social-twitter: jonatanaxe # add your Twitter handle
social-facebook: jonatanaxe # add your Facebook handle
social-github: jonatanaxe # add your Github handle
social-linkedin: jonatanaxe # add your Linkedin handle
social-email: web-jonatan@live.com # add your Email address

# Disqus
discus-identifier: jonatanmachado-tk # add your discus identifier

# Tracker
analytics: UA-124283707-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-sitemap

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
